### ISSUE TITLE
Change figure size

### ISSUE THREAD

**Issue by Marius1311** [theislab/interactive_plotting#14]
What's the easies way for the user to change the figure size? I call

```python
ipl.interactive_hist(adata, keys=['n_proteins', 'bad_struct', 'no_match', 'n_counts_prot'],
                            groups=['batch'])
```
and so I get four histograms, but they are too wide to fit my jupyter notebook.

**Comment by michalk8** [comment]
You can specify ```plot_width=``` and ```plot_height=``` to change the size of the figures (I think the units are pixels).

**Comment by Marius1311** [comment]
perfect, I will check it out!

**Comment by Marius1311** [comment]
Ok, works perfectly. I should have read the docstring, sorry about that!
