### ISSUE TITLE
highlight indices

### ISSUE THREAD

**Issue by Marius1311** [theislab/interactive_plotting#20]
`highlight_indices` need's key to plot - is that really necessary? If I just want to look at cells in a diffmap and choose a root cells based on that, that's okay, right? I would make it optional to specify a key, and if None is give, just plot the cells in gray.

**Comment by michalk8** [comment]
The key is used when you know and have the type of cell where the starting one should be.
Add `None` by default seems like a good option - I will add that.

**Comment by Marius1311** [comment]
Great! I know this feature makes total sense - I just think the user should be able to evoke the function without having to provide this argument.

**Comment by michalk8** [comment]
I've **removed** the `highlight_indices`, you should be now using `scatterc` to get the cell
indices. In the meantime, I will think about other cell-level annotations, whether they are even a good idea in the first place and if so, try to reintroduce them.
Closed via #26
