### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by Marius1311** [theislab/interactive_plotting#22]
What's conceptually the difference between the interactive scatter plots and `highlight_indices`? Could we combine these into one function?

**Comment by michalk8** [comment]
The interactive scatterplots can handle large amounts of cells, because in `holoviews`, they rasterize the plot, so there is no cell-level like information.
There's the possibility of cutting the plot into discrete blocks, from which I would take some index from cells belonging to that block. Other approach would be to heaviliy subsample and do similarly as in `highlight_indices`.

**Comment by Marius1311** [comment]
okay, mhm. Would `holoviews` give cell level info when I zoom in heavily, say to a view where I only have one cell?

**Comment by Marius1311** [comment]
Because in reality, when I have say 20k cells and I want to find a root cell, I would always choose the relevant clusters and zoom in heavily until I have like 10 cells in view and hoover over those to see their indices.

**Comment by michalk8** [comment]
> okay, mhm. Would `holoviews` give cell level info when I zoom in heavily, say to a view where I only have one cell?

Yes, that's possible. I've implemented the hover for `scatterc` only, should be working. Just specify `hover=True` or `hover=<NUM>`, where `<NUM>` is the number of blocks into which the plot will be cut (default is `10`).
If this works as you expect, I would retire (i.e. remove) `ipl.highlight_indices` and close this issue.

**Comment by Marius1311** [comment]
Okay great, I will check this out.

**Comment by Marius1311** [comment]
comments 
- typo in `scatterc`: "bases" instead of "basis"
- hoovering works
- the legend is very much in the way of the plot, see below:

![Screenshot 2019-11-18 at 13 53 53](https://user-images.githubusercontent.com/24494650/69080939-eec41500-0a0a-11ea-8261-c7a26693f582.png)

**Comment by Marius1311** [comment]
There is a lot of white space, yet the legend blocks out 2/3 of the data - could this somehow be changed? Even a button to hide the legend would help, or options to position it.

**Comment by Marius1311** [comment]
However, the actual issue is solved: I'm happy with the hovering, this works really well and can replace the `highlight_indices` function.

**Comment by Marius1311** [comment]
Maybe close this issue and make the legend a seperate one.

**Comment by Marius1311** [comment]
Also, the title of the plot isn't fully displayed, a new line would be good here.

**Comment by michalk8** [comment]
> There is a lot of white space, yet the legend blocks out 2/3 of the data - could this somehow be changed? Even a button to hide the legend would help, or options to position it.

You can always use `show_legend=False` to disable it entirely, or `legend_loc=...` to position it differently.

> However, the actual issue is solved: I'm happy with the hovering, this works really well and can replace the `highlight_indices` function.

Will do.

> Also, the title of the plot isn't fully displayed, a new line would be good here.

This is a bit tricky, since the title is autogenerated and at the moment, I'm not sure if I can access the formatter (at least easily). Will look into it.

**Comment by Marius1311** [comment]
okay, thanks!
