### ISSUE TITLE
scatterc basis specification

### ISSUE THREAD

**Issue by Marius1311** [theislab/interactive_plotting#24]
Why do I need to specify the basis I want to use? Can't it just load all available from .obsm and allow me to choose among them via the drop down?

**Comment by michalk8** [comment]
By default, `bases=None`, and as the docstring says, it will try to get all the bases available in `adata.obsm`.

**Comment by Marius1311** [comment]
okay, I see, great. Still, I would call it 'basis', even if you mean the plural, just because this is common in both scanpy and scvelo and users are familiar with it.
