### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by rsggsr** [theislab/interactive_plotting#36]
Hi,

Thanks for this interesting package. But I always get this error while importing, could you kindly help with this error? Thanks a lot!

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-e62e20c5358c> in <module>
----> 1 import interactive_plotting as ipl

~\Miniconda3\envs\project\lib\site-packages\interactive_plotting\__init__.py in <module>
----> 1 from .bokeh_plots import interactive_hist, \
      2                          thresholding_hist, \
      3                          highlight_de, \
      4                          link_plot, \
      5                          gene_trend

~\Miniconda3\envs\project\lib\site-packages\interactive_plotting\bokeh_plots.py in <module>
     23 
     24 
---> 25 from .utils import sample_unif, sample_density, to_hex_palette
     26 from bokeh.plotting import figure, show, save as bokeh_save
     27 from bokeh.models import ColumnDataSource, Slider, HoverTool, ColorBar, \

ModuleNotFoundError: No module named 'interactive_plotting.utils'

**Comment by le-ander** [comment]
Just wanted to try out the package and ran into the same issue. Any suggestions?

**Comment by Marius1311** [comment]
@michalk8 , could you have a look at this?

**Comment by michalk8** [comment]
@le-ander @rsggsr sorry it took me so long! I've just updated a few things, I think it should work (I was unable to replicate this myself though - I hope change from relative to absolute imports fixed that).

**Comment by le-ander** [comment]
Works! Thanks a lot @michalk8 :)

**Comment by PattF** [comment]
Hey guys, I'm getting the same error after trying to import interactive plotting.
I've installed through `pip install git+https://github.com/theislab/interactive_plotting`.
Any ideas how to fix?

Currently running python 3.6.10 with the current packages: scanpy==1.5.1 anndata==0.7.4 umap==0.4.6 numpy==1.18.1 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.8.2 leidenalg==0.8.1

Thanks beforehand!

**Comment by michalk8** [comment]
@PattF thanks for spotting this, should be fixed now (issue with setup.py). Also the import time is rather slow, due to the fact that node needs to compile the `TypeScript file for 3D scatterplot.
