### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Marius1311** [theislab/interactive_plotting#4]
Please provide a short description of what the package can do in the readme, maybe also with a couple of screenshots, looks nicer. You should stress that it harmonises perfectly with scanpy.

**Comment by michalk8** [comment]
The README.md has been updated, let me know if you have any suggestions/improvements.

**Comment by Marius1311** [comment]
Thanks Mike! 
2 comments on the README:
1.) Please mention the example notebook somewhere, e.g. in a section "Getting Started"
2.) Please rename the function "velocity_plot" to something like "gene_trend" because it's more descriptive
