### ISSUE TITLE
No output in notebook

### ISSUE THREAD

**Issue by Marius1311** [theislab/interactive_plotting#7]
For the functions link_plot and velocity_plot, I get the error:

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

**Comment by Marius1311** [comment]
@michalk8 please let me know when you think I should advertise the plotting functions in mattermost. I think we should first fix the most relevant issues like this one.

**Comment by michalk8** [comment]
This ought not to happen anymore, since the size of `link_plot` and `velocity_plot` has been reduced.
If it does, consider starting Jupyter notebook as:
```jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10```
